spring:
  env:
    jwt-secret-key: 'jwt-secret-key'
  datasource:
    url: 'jdbc:h2:mem:library'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

cloud:
  aws:
    s3:
      bucket: 'bucket-name'
    region:
      static: 'region-name'
    stack:
      auto: false
    credentials:
      accessKey: 'access-key'
      secretKey: 'secret-key'